"""Write results/EVIDENCE_LEDGER.md: every claim, the test behind it, the file, and which checks it survived.

Everything is read from the result tables, nothing is typed in by hand. A claim is "confirmed" only under the rule in
preregistration/PREREG_v1.3_confirmation.md (main test plus at least two of C1 to C4).

    python scripts/make_evidence_ledger.py
"""
from pathlib import Path

import numpy as np
import pandas as pd

import calibrate

RES = Path("D:/AAN/results")
DERIVED = Path("D:/AAN_data/derived")
TARGET = "decodeme_gwas_1"


def read(name, **kw):
    path = RES / name
    return pd.read_csv(path, sep="\t", **kw) if path.exists() else None


def loco_robust(cluster_ids):
    """Number of leave-one-chromosome-out runs in which each cluster keeps p < 0.05."""
    counts = pd.Series(0, index=cluster_ids)
    n_runs = 0
    for c in range(1, 23):
        try:
            m = calibrate.load_model(TARGET, f"loco_chr{c}") if calibrate.gsa_path(TARGET, f"loco_chr{c}") else None
        except Exception:
            m = None
        if m is None:
            continue
        n_runs += 1
        counts += (m["P"].reindex(cluster_ids) < 0.05).astype(int)
    return counts, n_runs


def main():
    clusters = read(f"clusters_{TARGET}.tsv", index_col="cluster_id")
    if clusters is None:
        print("no cluster table yet")
        return
    main_sig = clusters[(clusters["fdr_A"] < 0.05)].copy()
    rows = main_sig[["cluster_name", "supercluster", "z", "fdr_A", "p_B", "s", "T2_specific"]].copy() \
        if "p_B" in main_sig else main_sig[["cluster_name", "supercluster", "z", "fdr_A", "s", "T2_specific"]].copy()

    # C1 S-LDSC
    sl = read(f"sldsc_{TARGET}.tsv")
    if sl is not None:
        sl["cluster_id"] = sl["cluster"].str[1:].astype(int)
        sl = sl.set_index("cluster_id")
        rows["C1_sldsc_p"] = sl["p_one_sided"].reindex(rows.index)
        rows["C1"] = rows["C1_sldsc_p"] < 0.05
    # C2 permutation
    pm = read(f"permutation_{TARGET}.tsv")
    if pm is not None:
        pm["cluster_id"] = pm["cluster"].astype(str).str.lstrip("c").astype(int)
        pm = pm.set_index("cluster_id")
        rows["C2_perm_p"] = pm["empirical_p"].reindex(rows.index)
        rows["C2"] = rows["C2_perm_p"] < 0.05
    # C3 locus drop and leave-one-chromosome-out
    if calibrate.gsa_path(TARGET, "locusdrop"):
        ld = calibrate.load_model(TARGET, "locusdrop")
        rows["C3_locusdrop_p"] = ld["P"].reindex(rows.index)
        cnt, n_runs = loco_robust(rows.index)
        rows["C3_loco_runs_ok"] = cnt
        rows["C3"] = (rows["C3_locusdrop_p"] < 0.05) & (cnt >= max(n_runs - 2, 1))
    # C4 independent GWAS
    g2 = calibrate.gsa_path("decodeme_gwas_2", "A")
    if g2:
        m2 = calibrate.load_model("decodeme_gwas_2", "A")
        rows["C4_gwas2_p"] = m2["P"].reindex(rows.index)
        rows["C4"] = rows["C4_gwas2_p"] < 0.05

    checks = [c for c in ("C1", "C2", "C3", "C4") if c in rows]
    rows["checks_passed"] = rows[checks].sum(axis=1) if checks else 0
    rows["status"] = np.where(rows["checks_passed"] >= 2, "confirmed",
                              np.where(rows["checks_passed"] == 1, "partly supported", "not confirmed"))
    rows.to_csv(RES / "evidence_ledger_clusters.tsv", sep="\t", float_format="%.4g")

    lines = ["# Evidence ledger", "",
             "Generated by scripts/make_evidence_ledger.py from the files in results/. Nothing here is typed by hand.", "",
             f"Main test: ME/CFS ({TARGET}), MAGMA gene-property model A, BH-FDR < 0.05 across 461 clusters. "
             f"{len(rows)} clusters pass.", "",
             "Status rule (PREREG v1.3): confirmed = main test + at least two of C1 S-LDSC, C2 permutation, C3 locus and "
             "chromosome drop, C4 independent GWAS.", "",
             "| cluster | supercluster | z | FDR | specific (T2) | " + " | ".join(checks) + " | status |",
             "|---|---|---:|---:|:-:|" + ":-:|" * len(checks) + "---|"]
    for cid, r in rows.sort_values("z", ascending=False).iterrows():
        flags = " | ".join("yes" if r[c] else "no" for c in checks)
        lines.append(f"| {r['cluster_name']} | {r['supercluster']} | {r['z']:.2f} | {r['fdr_A']:.2g} | "
                     f"{'yes' if r['T2_specific'] else 'no'} | {flags} | {r['status']} |")
    for name, label in (("groups_A_decodeme_gwas_1.tsv", "D1 transmitter and subtype groups (model A)"),
                        ("hpa_decodeme_gwas_1.tsv", "D2 whole-body cell types"),
                        ("pathways_decodeme_gwas_1.tsv", "D3 pathways")):
        t = read(name, index_col=0)
        if t is not None:
            lines += ["", f"## {label}", "", f"{len(t)} tested. File: results/{name}"]
    (RES / "EVIDENCE_LEDGER.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote", RES / "EVIDENCE_LEDGER.md")
    print(rows["status"].value_counts().to_string())


if __name__ == "__main__":
    main()
